apiVersion: v1
kind: Secret
metadata:
  name: flaskapi-secrets
type: Opaque
data:
  db_root_password: cm9vdAo=
  db_user_password: cm9vdAo=
---
apiVersion: v1
kind: Secret
metadata:
  name: flaskapisecrets
type: Opaque
data:
  db_root_password: {{ .Values.app.db_root_password | b64enc | quote }}
  db_user_password: {{ .Values.app.db_user_password | b64enc | quote }}